### ISSUE TITLE
Pause/Play doesnt work on first time

### ISSUE THREAD

**Issue by waseem01** [quran/quran-ios#41] opened 2016-07-11 01:22 UTC
1. Launch app
2. Tap on Surah Baqarah
3. Tap play button at the bottom.
4. Observe, button first shows play mode and then changes to pause mode
5. Tap the button, the recitation doesnt stop, tap again, now it stops
6. This happens only first time for any surah when its loaded.

**Comment by waseem01** [comment] 2016-07-11 01:23
I will fix this inshaAllah, @mohamede1945 please add me to the project so I can assign it to myself

**Comment by ahmedre** [comment] 2016-07-11 01:59
@waseem01 @mohamede1945 i've added an "in progress" label that we can label things people are working on with instead of adding to the project.

**Comment by waseem01** [comment] 2016-07-11 02:24
@ahmedre Thanks, I dont have 'write permissions' to the repo to move it :)

**Comment by ahmedre** [comment] 2016-07-11 02:28
we're not adding people with write permissions to the project right now for a few reasons:
1. as a "github organization," we pay depending on the members in the organization
2. we want to restrict checkin permissions to the code so only approved pull requests get merged

i also looked to see if there's a way to just give permissions to add labels and what not, but i didn't see that, though i could have missed it.

**Comment by ahmedre** [comment] 2016-07-11 02:29
as an aside, most open source projects work this way - i.e. you don't get write permissions to most of the repositories to be able to contribute - the maintainers are responsible for looking at pull requests, reviewing them, and merging code accordingly.

**Comment by ahmedre** [comment] 2016-07-11 02:30
oh - and i forgot, most importantly - jazakAllah khairan in advance!

**Comment by waseem01** [comment] 2016-07-11 02:30
Thanks, I will open a PR and I guess the admin can merge.

**Comment by mohamede1945** [comment] 2016-07-11 19:30
@waseem01 I don't know why I'm not able to reproduce the issue. Can you have tell me which reciter were you using?

**Comment by mohamede1945** [comment] 2016-07-11 19:32
@ahmedre Thanks a lot for creating the label. I was mainly depending on zenhub for such things, but I think I should use labels too since it will be easier for everyone.

**Comment by mohamede1945** [comment] 2016-08-20 11:52
Gif of the issue:
![g7jxoq](https://cloud.githubusercontent.com/assets/20160610/16753775/327413c8-47b2-11e6-915d-8f9f1a88b37f.gif)

**Comment by mohamede1945** [comment] 2016-08-20 11:52
I'll start working on this issue now.

**Comment by mohamede1945** [comment] 2018-04-15 04:27
Can't reproduce anymore.

**Closed by mohamede1945** 2018-04-15 04:27 UTC
Labels: P3, bug
