### ISSUE TITLE
Tapped verse as starting point for audio playback

### ISSUE THREAD

**Issue by jayhub** [quran/quran-ios#119] opened 2017-04-13 22:31 UTC
User can choose to start audio playback from a specific verse instead of starting from the beginning. One reason why this is important is because if user wants to continue from where they have left off. This probably means that user will have to download the audio files first.

**Comment by ahmedre** [comment] 2017-04-14 05:11
on Android, we do this through long press on an ayah and then clicking the audio button - this opens a page where you can choose repeat options, etc. i think the Android ui could be improved but maybe you can look at it for some ideas

**Comment by mohamede1945** [comment] 2017-04-14 08:37
This is a duplicate of #89 and #90

**Comment by mohamede1945** [comment] 2017-05-01 17:54
Closing as Duplicate

**Closed by mohamede1945** 2017-05-01 17:54 UTC
Labels: duplicate, feature

**Comment by mohamede1945** [comment] 2018-04-14 22:13
Implemented in https://github.com/quran/quran-ios/pull/231 and will be available in the next release inshaa'Allah
