### ISSUE TITLE
Add mushaf with tajweed.

### ISSUE THREAD

**Issue by ravshansbox** [quran/quran-ios#332] opened 2020-04-16 17:38 UTC
Ability to choose mushaf would be nice, especially great if there is at least one mushaf with tajweed.

**Comment by ravshansbox** [comment] 2020-04-21 08:18
http://www.easyquran.com has ready to use high quality scanned pages.

**Comment by mohamede1945** [comment] 2022-01-01 20:35
Good suggestion! Thanks for the reference

**Comment by mohamede1945** [comment] 2022-01-01 20:57
Duplicate of #79

**Closed by mohamede1945** 2022-01-01 20:57 UTC
Labels: Support Different Mushafs

**Comment by ravshansbox** [comment] 2022-01-01 21:36
I'm not sure this is duplicate, tajweed mushaf was only one example. Actually I was referring more to old and new Madinah mushafs.

**Comment by mohamede1945** [comment] 2022-01-01 21:38
Oh, I see. These are also part of the plan as well inshaa'Allah. They are under [this label](https://github.com/quran/quran-ios/labels/Support%20Different%20Mushafs). Do you see something missing under that label?

**Comment by ravshansbox** [comment] 2022-01-01 22:43
@mohamede1945 ough, sorry, I should have searched before opening. Yes, I see, there is already an open issue (#196) related to this. Jazakalloh!
