### ISSUE TITLE
Husayri (Muhawwad, gapless) sync problem

### ISSUE THREAD

**Issue by selim** [quran/quran-ios#391] opened 2022-04-16 15:27 UTC
- goto hud ayah 56 (11:56)
- select ayah and play
- app playing previous ayah while focusing current ayah

this case just for Husayri (mujawwad, gapless)

**Comment by mohamede1945** [comment] 2022-04-17 16:59
Thanks a lot for reporting this! I can reproduce it.

@ahmedre this seems to be 2 problems with the audio:
1) Hud ayah 23: it says (صدق الله العظيم)
2) It then moves to ayah 24 reciting verse 23. Then the recitation is always shifted by 1 verse until the end of the surah.

**Comment by ahmedre** [comment] 2022-04-17 20:35
jazakumAllah khairan, should be fixed now - got the report and fix from a brother working on another app earlier but didn't get a chance to upload until now.

**Closed by ahmedre** 2022-04-17 20:35 UTC
Labels: bug, Quran.com
