### ISSUE TITLE
Word for Word Audio

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [quran/quran-ios#167] opened 2017-05-28 19:01 UTC
Add Quran word for word audio support - https://archive.org/details/ibrahim_ahmed

I have already split the audio into individual audio files and the actual data is available here https://github.com/GlobalQuran/mushaf/blob/master/word-for-word-timing.xlsx

**Comment by mohamede1945** [comment] 2017-05-29 07:49
Jazak Allah khyran for this suggestion too! Actually, it would be awesome to have something like that. While I'm not the best person to respond here, @ahmedre will be more helpful and knowledgeable to tell us what exactly is needed to support that.

I just noticed 2 things in the data you are giving us:
1. The audio might have a problem because it is only outputted to one ear of my headset.
2. You only have that for 1 qari/reciter, correct?

**Comment by ahmedre** [comment] 2017-05-29 07:55
jazakAllah khairan - we actually have word by word data for all the shuyookh that are on quran.com (though not all the shuyookh in the mobile apps). with this, we can highlight each word as the sheikh plays it. insha'Allah we plan on doing this sometime in the near future insha'Allah.

**Comment by mohamede1945** [comment] 2017-05-29 07:57
Awesome! Thank you so much! I will keep this issue to track our progress of word-by-word audio.

**Comment by Ashraf-Ali-aa** [comment] 2017-05-29 20:03
@mohamede1945 currently is is mono sound but I can convert into stereo sound, also I do have a couple of other reciters like https://archive.org/details/Maher_Al_Moakly https://archive.org/details/Mohamed_Seddek_Al_Menshawy (text data included)

**Comment by mohamede1945** [comment] 2018-04-15 04:28
Duplicate of https://github.com/quran/quran-ios/issues/85

**Closed by mohamede1945** 2018-04-15 04:28 UTC
Labels: feature
